### ISSUE TITLE
Typo in the sidebar - TRO instead of RTO

### ISSUE THREAD

**Issue by netapp-chandaj** [NetAppDocs/ontap-apps-dbs#11]
### Summary

https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-dp-slas.html#recovery-point-objective
The short title of this page in the left menu says TRO instead of RTO.  Small typo.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by jfsinmsp** [comment]
Fixed in preproduction.
