### ISSUE TITLE
Update performance stats for Oracle

### ISSUE THREAD

**Issue by loran-penguin** [NetAppDocs/ontap-apps-dbs#14]
### Page URL

https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-notes-optimization-and-benchmarking.html

### Page title

Oracle performance optimization and benchmarking

### Summary

As title said, the performance docs for Oracle shows performance testing for AFF8080.   The AFF8080 is outdated and doesn't show the capabilities that can be for the newer models.
In addition, there is no further information on ONTAP version or DB type (single instance/RAC).

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by jfsinmsp** [comment]
Fixed in preprod. This particular section isn't about official stats, it's really about procedures used to compare arrays, but I did update it with more current models and statistics.
