### ISSUE TITLE
Typo in web page title metadata "Iracle" should be "Oracle"

### ISSUE THREAD

**Issue by estarz** [NetAppDocs/ontap-apps-dbs#17]
### Page URL

https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-migration-planning.html

### Page title

Iracle migration planning

### Summary

Web page title says Iracle...
<img width="178" alt="Screenshot 2024-02-13 at 17 44 40" src="https://github.com/NetAppDocs/ontap-apps-dbs/assets/2291693/4af10c3a-b44f-43b8-ac56-8b01be8a2bcf">
<img width="576" alt="Screenshot 2024-02-13 at 17 45 08" src="https://github.com/NetAppDocs/ontap-apps-dbs/assets/2291693/cc7d1c72-4e03-4acb-bfe9-6610e43aec7d">

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by jfsinmsp** [comment]
Fixed in preprod
