### ISSUE TITLE
Need updated reference for max LUN size with ONTAP

### ISSUE THREAD

**Issue by DrKeno** [NetAppDocs/ontap-apps-dbs#31]
### Page URL

https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-vsphere-datastores-san.html

### Page title

SAN (FC, FCoE, NVMe/FC, iSCSI), RDM

### Summary

This section of the documentation needs to be revamped for ONTAP 9.12.1P2 where the maximum LUN size for VMware is 64TB on all platforms.  We should also reference VMFS 5 / VMFS 6 to be current with the VMFS versions in use today.

Currently, the documentation reads:
The ONTAP maximum LUN size is generally 16TB; therefore, a maximum-size VMFS 5 datastore of 64TB (see the first table in this section) is created by using four 16TB LUNs (All SAN Array systems support the maximum VMFS LUN size of 64TB). 

Suggested update:
With ONTAP version 9.12.1P2, the maximum LUN size is 128TB on all platforms (AFF, ASA, & FAS) supported with ONTAP 9.12.1P2.  ONTAP version 9.12.1P2 and above supports the maximum VMFS 5 & VMFS 6 datastore of 64TB in a single LUN.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bingen** [comment]
Ok, I just fixed it in an internal branch. I will try to publish in a few days.
