### ISSUE TITLE
Why is the default value of Net.TcpipHeapMax changed from TR-4597 ?

### ISSUE THREAD

**Issue by takehirs** [NetAppDocs/ontap-apps-dbs#41]
### Page URL

https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-vsphere-settings.html

### Page title

Recommended ESXi host and other ONTAP settings

### Summary

Why is the default value of Net.TcpipHeapMax changed from TR-4597 ?
In the TR-4597 documentation, it was changed to Net.TcpipHeapMax vSphere 6.0 later 1536MB, and in this latest this Docs it was changed to Set to 1024MB for 6.5U3, 6.7U3, and 7.0 or later. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bingen** [comment]
Yes, VMware's guidance is to use the default value in those releases. Although it doesn't mention it in our doc, 1024 is actually the new default.

I will add a note to the docs and publish that out this week.
