### ISSUE TITLE
Very minor typo in Oracle database efficiency doc

### ISSUE THREAD

**Issue by cwaltham** [NetAppDocs/ontap-apps-dbs#50]
### Page URL

https://docs.netapp.com/us-en/ontap-apps-dbs/oracle/oracle-ontap-config-efficiency.html

### Page title

Oracle databases and ONTAP efficiency features

### Summary

This is the current wording:

> Temperature sensitive storage efficiency (TSSE) is a available in ONTAP 9.8 and later that relies on block access heat maps to identify infrequently accessed blocks and compress them with greater efficiency.

The typo is "is a available".

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by jfsinmsp** [comment]
Thanks, fixed in internal, will push to public in the near future.
