### ISSUE TITLE
9.15.1 GA for SM-AS Symmetric

### ISSUE THREAD

**Issue by SPGoetze** [NetAppDocs/ontap-apps-dbs#51]
### Page URL

https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware_vmsc_overview.html

### Page title

vSphere Metro Storage Cluster with ONTAP

### Summary

SnapMirror active sync can also be deployed in two different ways.

    Asymmetric

    Symmetric _(private preview in ONTAP 9.14.1)_

**Symmetric is GA in 9.15.1**

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by jfsinmsp** [comment]
I'll take this one. I'm writing SMas content right now for SQL and Oracle anyway.

**Comment by jfsinmsp** [comment]
Resolved in staging, and will follow up with Chance on Monday.
