### ISSUE TITLE
Link at bottom should be reformatted to conform to docs.netapp.com standards

### ISSUE THREAD

**Issue by adamn-netapp** [NetAppDocs/ontap-apps-dbs#56]
### Page URL

https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware_vmsc_overview.html

### Page title

vSphere Metro Storage Cluster with ONTAP

### Summary

This article ends with the following sentence:

Refer to [NetApp Docs](https://docs.netapp.com/us-en/ontap/smbc/index.html) for specific design and deployment information for SnapMirror active sync.

Please reformat it as follows:

For more information about _XXXX_ design and deployment, see the [SnapMirror active sync documentation](https://docs.netapp.com/us-en/ontap/smbc/index.html).

Where _XXXX_ clarifies what design and deployment we're talking about. The doc as it's written currently is unclear.

Maybe it should be the following?

For more information about the advantages of symmetric or asymmetric design and deployment, see the [SnapMirror active sync documentation](https://docs.netapp.com/us-en/ontap/smbc/index.html).

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bingen** [comment]
Fixed in current internal branch.
